# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccc', '0003_auto_20160527_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_wanted', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='选购数量')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('submitted_date', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('canceled_date', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='总计')),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='运费')),
                ('transport_number', models.CharField(blank=True, max_length=128, verbose_name='快递单号')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='订单总价（含运费）')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, unique=True, verbose_name='产品名称')),
                ('product_description', models.TextField(max_length=1024, verbose_name='产品描述')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='库存数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='产品单价')),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='产品折扣')),
                ('reserved_quantity', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='冻结数量')),
                ('status', models.BooleanField(default=True, verbose_name='产品上架')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('cr_reason', models.CharField(max_length=512, verbose_name='变更原因')),
                ('rec_pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oms.Product', verbose_name='产品名称')),
                ('user_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc.SYUser', verbose_name='管理员')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('phone', models.CharField(max_length=15, verbose_name='电话号码')),
                ('address', models.CharField(max_length=120, verbose_name='邮寄地址')),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc.SYUser', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.RetailerInfo', verbose_name='收货人信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc.SYUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oms.Order', verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pro_selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc.SYUser', verbose_name='用户'),
        ),
    ]
