# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='最多1024个字符', max_length=64, unique=True, verbose_name='产品名称'),
        ),
    ]
