# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_auto_20160527_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='产品名称'),
        ),
    ]
