# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='反馈日期')),
                ('fv', models.CharField(blank=True, max_length=64, verbose_name='燃值')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='体重')),
                ('sbp', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='SBP（收缩压）')),
                ('dbp', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='DBP（舒张压）')),
                ('bp_time', models.TimeField(blank=True, verbose_name='血压测量时间')),
                ('fbg', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='FBG(空腹血糖)')),
                ('pbg', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='PBG(餐后血糖)')),
                ('bg_time', models.TimeField(blank=True, verbose_name='血糖测量时间')),
                ('sports_time', models.TimeField(blank=True, verbose_name='有氧运动时间')),
                ('op_react', models.TextField(blank=True, max_length=128, verbose_name='调理反应')),
                ('other_dis', models.TextField(blank=True, max_length=256, verbose_name='其它不适')),
                ('feedback', models.TextField(blank=True, max_length=256, verbose_name='体会及反馈')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('phone_number', models.CharField(max_length=15, verbose_name='电话号码')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='加入日期')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='体重')),
                ('height', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='身高')),
                ('bmi', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='BMI:(体重(KG)/身高×身高(M))')),
                ('hr', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='心率')),
                ('sbp', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='SBP（收缩压）')),
                ('dbp', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='DBP（舒张压）')),
                ('tc', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='TC（总胆固醇）')),
                ('tg', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='TG（甘油三脂）')),
                ('hdl', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='HDL（高密度脂蛋白）')),
                ('ldl', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='LDL（低密度脂蛋白）')),
                ('glu', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='GLU(随机血糖)')),
                ('fbg', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='FBG(空腹血糖)')),
                ('pbg', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='PBG(餐后血糖)')),
                ('a1c', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='A1C')),
                ('ir', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='胰岛素抵抗(IR)')),
                ('hcy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='同型半胱氨酸')),
                ('bua', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='血尿酸')),
                ('vfp', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='内脏脂肪占比')),
                ('imt', models.CharField(blank=True, max_length=128, verbose_name='IMT(颈动脉斑块)')),
                ('up', models.CharField(blank=True, max_length=128, verbose_name='尿蛋白')),
                ('lf', models.CharField(blank=True, max_length=128, verbose_name='肝功')),
                ('rf', models.CharField(blank=True, max_length=128, verbose_name='肾功')),
                ('uran', models.TextField(blank=True, max_length=128, verbose_name='尿液分析')),
                ('ba', models.TextField(blank=True, max_length=128, verbose_name='血液分析')),
                ('cons', models.TextField(blank=True, max_length=64, verbose_name='便秘')),
                ('frve', models.TextField(blank=True, max_length=128, verbose_name='蔬菜和水果')),
                ('dietfood', models.TextField(blank=True, max_length=128, verbose_name='忌口的食物')),
                ('cdh', models.TextField(blank=True, max_length=512, verbose_name='现病史')),
                ('ph', models.TextField(blank=True, max_length=512, verbose_name='既往史')),
                ('fh', models.TextField(blank=True, max_length=512, verbose_name='家族史')),
                ('oh', models.TextField(blank=True, max_length=512, verbose_name='手术史')),
                ('au', models.ImageField(blank=True, upload_to='au/', verbose_name='腹部彩超')),
                ('ecg', models.ImageField(blank=True, upload_to='ecg/', verbose_name='心电图')),
            ],
        ),
        migrations.CreateModel(
            name='SYUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('R', '经销商'), ('C', '终端用户'), ('A', '管理员')], default='C', max_length=1, verbose_name='用户类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '双圆健康用户',
            },
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='user_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc.SYUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='cust_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc.CustomerInfo', verbose_name='用户'),
        ),
    ]
