# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='bg_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='测量时间'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='bp_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='测量时间'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='sports_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='有氧运动时间'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='user_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc.SYUser', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='syuser',
            name='user_type',
            field=models.CharField(choices=[('R', '经销商'), ('C', '终端用户'), ('A', '管理员')], max_length=1, verbose_name='用户类型'),
        ),
    ]
