# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0002_auto_20160527_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='cust_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc.CustomerInfo', verbose_name='用户基本信息'),
        ),
    ]
